Add alternative configurations, add throwing exceptions to Config class
yiisoft/config pull request #64
Opened 2021-05-19 16:10 UTC by devanych

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #14

> Alternative configurations complement (do not override) the main configuration.

Adding it to `composer.json` for the root package:

```json
"config-plugin-alternatives": {
    "alfa": {
        "params": "config/alfa/params.php",
        "web": "config/alfa/web.php",
        "main": [
            "$web",
            "config/alfa/main.php"
        ]
    }
},
```

Getting the configuration of the alternative build group:

```php
// 'main' - the group name.
// 'alfa' - the build name.
$config->get('main', 'alfa');
```

Getting the configuration of the root build group:

```php
$config->get($groupName);
```

2021-05-27 20:18 UTC, samdark commented
@yiiliveext suggests to rename "alternatives" to "environments".

2021-05-29 12:24 UTC, vjik requested changes
Don't work if application use option `source-directory`.

Error:

```
λ yii serve

Fatal error: Uncaught ErrorException: The "/" configuration build does not exist. in E:\open-source\yiisoft\yii-dev-tool\dev\config\src\Config.php on line 365

ErrorException: The "/" configuration build does not exist. in E:\open-source\yiisoft\yii-dev-tool\dev\config\src\Config.php on line 365

Call Stack:
    0.0003     405976   1. {main}() E:\open-source\yiisoft\yii-dev-tool\dev\demo\yii:0
    0.0538    4844960   2. Yiisoft\Config\Config->get($group = 'console', $build = ???) E:\open-source\yiisoft\yii-dev-tool\dev\demo\yii:22
    0.0538    4844960   3. Yiisoft\Config\Config->buildGroup($group = 'params', $build = '/', $rootBuildGroupConfig = ???) E:\open-source\yiisoft\yii-dev-tool\dev\config\src\Config.php:68
    0.0538    4844960   4. Yiisoft\Config\Config->checkBuildGroup($group = 'params', $build = '/') E:\open-source\yiisoft\yii-dev-tool\dev\config\src\Config.php:101
    0.0538    4845280   5. Yiisoft\Config\Config->throwException($message = 'The "/" configuration build does not exist.') E:\open-source\yiisoft\yii-dev-tool\dev\config\src\Config.php:314
```

2021-05-29 12:31 UTC, devanych commented
> Don't work if application use option `source-directory`.

Did you regenerate merge_plan.php?

This PR changes its format.

2021-05-29 12:43 UTC, vjik commented
> > Don't work if application use option `source-directory`.
> 
> Did you regenerate merge_plan.php?
> 
> This PR changes its format.

Oh, sorry. Yes, it's work.

2021-05-29 12:54 UTC, vjik requested changes
When getting alternative configuration `params` from alternatives should merged with `params` from general configuration and then pass both to general configs and alternative configs.

Now merged params pass only to alternative configs. In general configs pass only general params. This is wrong behavior.

2021-05-29 14:59 UTC, devanych commented
> When getting alternative configuration `params` from alternatives should merged with `params` from general configuration and then pass both to general configs and alternative configs.
> 
> Now merged params pass only to alternative configs. In general configs pass only general params. This is wrong behavior.

Done.

2021-05-29 16:33 UTC, devanych commented
> @yiiliveext suggests to rename "alternatives" to "environments".

Done.

2021-05-29 17:08 UTC, vjik commented on src/Config.php
> +    private function checkVariable(string $variable, string $group, string $environment): string
May be better name `prepareVariable()` ?

2021-05-29 17:08 UTC, vjik commented on src/Config.php
> +    private function checkEnvironmentGroup(string $group, string $environment): string
Maybe better name `prepareEnvironmentGroup()` ?

2021-05-29 17:08 UTC, vjik commented on tests/Integration/PackagesListBuilderTest.php
> +                    Options::DEFAULT_ENVIRONMENT => [
Seems here `Options::DEFAULT_ENVIRONMENT` not environment. This is application files for config. May be create new constant for this?

2021-05-29 17:08 UTC, vjik commented on tests/Integration/PackagesListBuilderTest.php
> +                    Options::DEFAULT_ENVIRONMENT => [
Seems here `Options::DEFAULT_ENVIRONMENT` not environment. This is application files for config. May be create new constant for this?

2021-05-29 17:08 UTC, vjik commented on tests/Integration/PackagesListBuilderTest.php
> +                    Options::DEFAULT_ENVIRONMENT => [
Seems here `Options::DEFAULT_ENVIRONMENT` not environment. This is application files for config. May be create new constant for this?

2021-05-29 17:08 UTC, vjik commented on tests/Integration/PackagesListBuilderTest.php
> +                    Options::DEFAULT_ENVIRONMENT => [
Seems here `Options::DEFAULT_ENVIRONMENT` not environment. This is application files for config. May be create new constant for this?

2021-05-29 17:08 UTC, vjik commented on tests/Integration/PackagesListBuilderTest.php
> +                    Options::DEFAULT_ENVIRONMENT => [
Seems here `Options::DEFAULT_ENVIRONMENT` not environment. This is application files for config. May be create new constant for this?

2021-05-29 17:08 UTC, vjik commented on tests/Integration/PackagesListBuilderTest.php
> +                    Options::DEFAULT_ENVIRONMENT => [
Seems here `Options::DEFAULT_ENVIRONMENT` not environment. This is application files for config. May be create new constant for this?

2021-05-29 17:08 UTC, vjik commented on tests/Integration/PackagesListBuilderTest.php
> +                    Options::DEFAULT_ENVIRONMENT => [
Seems here `Options::DEFAULT_ENVIRONMENT` not environment. This is application files for config. May be create new constant for this?

2021-05-29 17:08 UTC, vjik commented on tests/Integration/PackagesListBuilderTest.php
> +                    Options::DEFAULT_ENVIRONMENT => [
Seems here `Options::DEFAULT_ENVIRONMENT` not environment. This is application files for config. May be create new constant for this?

2021-05-29 17:08 UTC, vjik commented on tests/Integration/PackagesListBuilderTest.php
> +                    Options::DEFAULT_ENVIRONMENT => [
Seems here `Options::DEFAULT_ENVIRONMENT` not environment. This is application files for config. May be create new constant for this?

2021-05-29 17:08 UTC, vjik commented on tests/Integration/PackagesListBuilderTest.php
> +                    Options::DEFAULT_ENVIRONMENT => [
Seems here `Options::DEFAULT_ENVIRONMENT` not environment. This is application files for config. May be create new constant for this?

2021-05-29 17:08 UTC, vjik commented on tests/Unit/ComposerConfigProcessTest.php
> +                    Options::DEFAULT_ENVIRONMENT => [
Seems here `Options::DEFAULT_ENVIRONMENT` not environment. This is application files for config. May be create new constant for this?

2021-05-29 17:56 UTC, vjik approved these changes

2021-05-29 17:56 UTC, vjik commented on src/Config.php
> +     * @param string $packageName Name of the package. {@see Options::DEFAULT_ENVIRONMENT} stands for the root package.
```suggestion
     * @param string $packageName Name of the package. {@see Options::ROOT_PACKAGE_NAME} stands for the root package.
```

2021-05-29 17:56 UTC, vjik commented on src/Config.php
> +     * @param string $packageName Name of the package. {@see Options::DEFAULT_ENVIRONMENT} stands for the root package.
```suggestion
     * @param string $packageName Name of the package. {@see Options::ROOT_PACKAGE_NAME} stands for the root package.
```

2021-05-29 21:16 UTC, samdark approved these changes

2021-05-29 21:17 UTC, merged

2021-05-29 21:17 UTC, samdark commented
👍