Renaming configDir for removed packages
yiisoft/config pull request #9
Opened 2021-02-09 16:23 UTC by darkdef

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #2 
Renaming dir with config for removed packages to packageName.removed

2021-02-09 22:47 UTC, samdark approved these changes
Looks good except method name.

2021-02-09 22:47 UTC, samdark commented on src/ComposerEventHandler.php
> +            $this->removePackageConfig($packageName, $outputDirectory);
```suggestion
            $this->markPackageConfigAsRemoved($packageName, $outputDirectory);
```

2021-02-13 20:34 UTC, darkdef commented on src/ComposerEventHandler.php
> +            $this->removePackageConfig($packageName, $outputDirectory);
ok

2021-02-14 09:00 UTC, samdark requested changes

2021-02-14 09:00 UTC, samdark commented on tests/Integration/ComposerEventHandlerTest.php
> +        $this->exec("rm -rf $workingDirectory/*");
Won't work with Windows. Let's require-dev yiisoft/files and use `FileHelper::removeDirectory()`.

2021-02-14 18:36 UTC, samdark approved these changes

2021-02-14 18:37 UTC, merged

2021-02-14 18:37 UTC, samdark commented
👍